This problem was asked by Facebook.
Given an N by N matrix, rotate it by 90 degrees clockwise.
For example, given the following matrix:

This problem was asked by Facebook.
Given an N by N matrix, rotate it by 90 degrees clockwise.
For example, given the following matrix:
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
you should return:
[[7, 4, 1],
 [8, 5, 2],
 [9, 6, 3]]

In [43]:
import numpy as np
array=np.array([ [1, 2, 3,  4],
                 [5, 6, 7,  8],
                 [9, 10,11,12],
                 [13,14,15,16]])
N=array.shape[0]
print(np.array([array[i][j] for j in range(N) for i in range(N - 1, -1, -1)]).reshape(array.shape))

[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
